/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 12-Jun-2026 17:13:29 */
/* MATLAB Version: 9.14.0.2891782 (R2023a) Update 8 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#include "carFollow_fis.h"
#include "core/qfis.h"

/* FIS Object */
static qFIS_t carFollow;
/* I/O Fuzzy Objects */
static qFIS_Input_t carFollow_inputs[2];
static qFIS_Output_t carFollow_outputs[1];
/* I/O Membership Objects */
static qFIS_MF_t MFin[6], MFout[9];
/* I/O Names */
enum { relDistance, relSpeed };
enum { Acceleration };
/* I/O Membership functions tags */
enum { relDistance_close, relDistance_far, relDistance_out_of_range, relSpeed_slow, relSpeed_medium, relSpeed_fast };
enum { Acceleration_out1mf1, Acceleration_out1mf2, Acceleration_out1mf3, Acceleration_out1mf4, Acceleration_out1mf5, Acceleration_out1mf6, Acceleration_out1mf7, Acceleration_out1mf8, Acceleration_out1mf9 };
/* Rules of the inference system */
static const qFIS_Rules_t rules[] = {
	QFIS_RULES_BEGIN
	   IF relDistance IS relDistance_close AND relSpeed IS relSpeed_slow THEN Acceleration IS Acceleration_out1mf1 END
	   IF relDistance IS relDistance_close AND relSpeed IS relSpeed_medium THEN Acceleration IS Acceleration_out1mf2 END
	   IF relDistance IS relDistance_close AND relSpeed IS relSpeed_fast THEN Acceleration IS Acceleration_out1mf3 END
	   IF relDistance IS relDistance_far AND relSpeed IS relSpeed_slow THEN Acceleration IS Acceleration_out1mf4 END
	   IF relDistance IS relDistance_far AND relSpeed IS relSpeed_medium THEN Acceleration IS Acceleration_out1mf5 END
	   IF relDistance IS relDistance_far AND relSpeed IS relSpeed_fast THEN Acceleration IS Acceleration_out1mf6 END
	   IF relDistance IS relDistance_out_of_range AND relSpeed IS relSpeed_slow THEN Acceleration IS Acceleration_out1mf7 END
	   IF relDistance IS relDistance_out_of_range AND relSpeed IS relSpeed_medium THEN Acceleration IS Acceleration_out1mf8 END
	   IF relDistance IS relDistance_out_of_range AND relSpeed IS relSpeed_fast THEN Acceleration IS Acceleration_out1mf9 END
	QFIS_RULES_END
};
/* Rule strengths */
float rFollowStrength[9] = { 0.0f };

/* Parameters of the membership functions */
static const float relDistance_close_p[] = { 21.1829f, 0.0139f };
static const float relDistance_far_p[] = { 21.2156f, 50.0796f };
static const float relDistance_out_of_range_p[] = { 21.3437f, 99.9480f };
static const float relSpeed_slow_p[] = { 4.6964f, -0.4473f };
static const float relSpeed_medium_p[] = { 4.5057f, 7.8219f };
static const float relSpeed_fast_p[] = { 4.5874f, 16.5995f };
static const float Acceleration_out1mf1_p[] = { -0.0320f, -15.5881f, -26.7785f };
static const float Acceleration_out1mf2_p[] = { 0.3601f, -19.0550f, 135.4324f };
static const float Acceleration_out1mf3_p[] = { -1.2830f, -23.9156f, 402.0150f };
static const float Acceleration_out1mf4_p[] = { -0.1158f, -4.1671f, -5.3482f };
static const float Acceleration_out1mf5_p[] = { 0.0827f, -5.1551f, 38.1144f };
static const float Acceleration_out1mf6_p[] = { -0.4825f, -2.7087f, 75.8812f };
static const float Acceleration_out1mf7_p[] = { -0.0450f, 5.7311f, 24.8847f };
static const float Acceleration_out1mf8_p[] = { -0.6328f, 7.2596f, -18.3228f };
static const float Acceleration_out1mf9_p[] = { -0.6343f, 3.1176f, -0.9114f };

void carFollow_init(void) {
	/* Set inputs */
	qFIS_InputSetup(carFollow_inputs, relDistance, 0.0010f, 100.0000f);
	qFIS_InputSetup(carFollow_inputs, relSpeed, 0.0000f, 17.1687f);
	/* Set outputs */
	qFIS_OutputSetup(carFollow_outputs, Acceleration, -5.5000f, 3.5000f);
	/* Set membership functions for the inputs */
	qFIS_SetMF(MFin, relDistance, relDistance_close, gaussmf, NULL, relDistance_close_p, 1.0f);
	qFIS_SetMF(MFin, relDistance, relDistance_far, gaussmf, NULL, relDistance_far_p, 1.0f);
	qFIS_SetMF(MFin, relDistance, relDistance_out_of_range, gaussmf, NULL, relDistance_out_of_range_p, 1.0f);
	qFIS_SetMF(MFin, relSpeed, relSpeed_slow, gaussmf, NULL, relSpeed_slow_p, 1.0f);
	qFIS_SetMF(MFin, relSpeed, relSpeed_medium, gaussmf, NULL, relSpeed_medium_p, 1.0f);
	qFIS_SetMF(MFin, relSpeed, relSpeed_fast, gaussmf, NULL, relSpeed_fast_p, 1.0f);
	/* Set membership functions for the outputs */
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf1, linearmf, NULL, Acceleration_out1mf1_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf2, linearmf, NULL, Acceleration_out1mf2_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf3, linearmf, NULL, Acceleration_out1mf3_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf4, linearmf, NULL, Acceleration_out1mf4_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf5, linearmf, NULL, Acceleration_out1mf5_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf6, linearmf, NULL, Acceleration_out1mf6_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf7, linearmf, NULL, Acceleration_out1mf7_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf8, linearmf, NULL, Acceleration_out1mf8_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf9, linearmf, NULL, Acceleration_out1mf9_p, 1.0f);

	/* Configure the Inference System */
	qFIS_Setup(&carFollow, Sugeno,
		carFollow_inputs, sizeof(carFollow_inputs),
		carFollow_outputs, sizeof(carFollow_outputs),
		MFin, sizeof(MFin), MFout, sizeof(MFout),
		rules, rFollowStrength, 9u);
	qFIS_SetParameter(&carFollow, qFIS_AND, qFIS_PROD);
	qFIS_SetParameter(&carFollow, qFIS_OR, qFIS_PROBOR);
	qFIS_SetParameter(&carFollow, qFIS_Implication, qFIS_PROD);
	qFIS_SetParameter(&carFollow, qFIS_Aggregation, qFIS_SUM);
}

void carFollow_run(float* inputs, float* outputs) {
	/* Set the crips inputs */
	qFIS_SetInput(carFollow_inputs, relDistance, inputs[relDistance]);
	qFIS_SetInput(carFollow_inputs, relSpeed, inputs[relSpeed]);

	qFIS_Fuzzify(&carFollow);
	if (qFIS_Inference(&carFollow) > 0) {
		qFIS_DeFuzzify(&carFollow);
	}
	else {
		/* Error! */
	}

	/* Get the crips outputs */
	outputs[Acceleration] = qFIS_GetOutput(carFollow_outputs, Acceleration);
}