/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 12-Jun-2026 17:13:29 */
/* MATLAB Version: 9.14.0.2891782 (R2023a) Update 8 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#ifndef CARFOLLOW_FIS_H
#define CARFOLLOW_FIS_H

#ifdef __cplusplus
    extern "C" {
#endif

    void carFollow_init( void );
    void carFollow_run( float *inputs, float *outputs );

#ifdef __cplusplus
    }
#endif

#endif /* CARFOLLOW_FIS_H */
