/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 11-Jun-2026 22:53:25 */
/* MATLAB Version: 9.14.0.2891782 (R2023a) Update 8 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#ifndef HEADTOHEAD_FIS_H
#define HEADTOHEAD_FIS_H

#ifdef __cplusplus
    extern "C" {
#endif

    void headtohead_init( void );
    void headtohead_run( float *inputs, float *outputs );

#ifdef __cplusplus
    }
#endif

#endif /* HEADTOHEAD_FIS_H */
