/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 11-Jun-2026 22:53:25 */
/* MATLAB Version: 9.14.0.2891782 (R2023a) Update 8 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#include "headtohead_fis.h"
#include "core/qfis.h"

/* FIS Object */
static qFIS_t headtohead;
/* I/O Fuzzy Objects */
static qFIS_Input_t headtohead_inputs[2];
static qFIS_Output_t headtohead_outputs[1];
/* I/O Membership Objects */
static qFIS_MF_t MFin[10], MFout[25];
/* I/O Names */
enum { input1, input2 };
enum { output };
/* I/O Membership functions tags */
enum { input1_in1mf1, input1_in1mf2, input1_in1mf3, input1_in1mf4, input1_in1mf5, input2_in2mf1, input2_in2mf2, input2_in2mf3, input2_in2mf4, input2_in2mf5 };
enum { output_out1mf1, output_out1mf2, output_out1mf3, output_out1mf4, output_out1mf5, output_out1mf6, output_out1mf7, output_out1mf8, output_out1mf9, output_out1mf10, output_out1mf11, output_out1mf12, output_out1mf13, output_out1mf14, output_out1mf15, output_out1mf16, output_out1mf17, output_out1mf18, output_out1mf19, output_out1mf20, output_out1mf21, output_out1mf22, output_out1mf23, output_out1mf24, output_out1mf25 };
/* Rules of the inference system */
static const qFIS_Rules_t rules[] = {
	QFIS_RULES_BEGIN
	   IF input1 IS input1_in1mf1 AND input2 IS input2_in2mf1 THEN output IS output_out1mf1 END
	   IF input1 IS input1_in1mf1 AND input2 IS input2_in2mf2 THEN output IS output_out1mf2 END
	   IF input1 IS input1_in1mf1 AND input2 IS input2_in2mf3 THEN output IS output_out1mf3 END
	   IF input1 IS input1_in1mf1 AND input2 IS input2_in2mf4 THEN output IS output_out1mf4 END
	   IF input1 IS input1_in1mf1 AND input2 IS input2_in2mf5 THEN output IS output_out1mf5 END
	   IF input1 IS input1_in1mf2 AND input2 IS input2_in2mf1 THEN output IS output_out1mf6 END
	   IF input1 IS input1_in1mf2 AND input2 IS input2_in2mf2 THEN output IS output_out1mf7 END
	   IF input1 IS input1_in1mf2 AND input2 IS input2_in2mf3 THEN output IS output_out1mf8 END
	   IF input1 IS input1_in1mf2 AND input2 IS input2_in2mf4 THEN output IS output_out1mf9 END
	   IF input1 IS input1_in1mf2 AND input2 IS input2_in2mf5 THEN output IS output_out1mf10 END
	   IF input1 IS input1_in1mf3 AND input2 IS input2_in2mf1 THEN output IS output_out1mf11 END
	   IF input1 IS input1_in1mf3 AND input2 IS input2_in2mf2 THEN output IS output_out1mf12 END
	   IF input1 IS input1_in1mf3 AND input2 IS input2_in2mf3 THEN output IS output_out1mf13 END
	   IF input1 IS input1_in1mf3 AND input2 IS input2_in2mf4 THEN output IS output_out1mf14 END
	   IF input1 IS input1_in1mf3 AND input2 IS input2_in2mf5 THEN output IS output_out1mf15 END
	   IF input1 IS input1_in1mf4 AND input2 IS input2_in2mf1 THEN output IS output_out1mf16 END
	   IF input1 IS input1_in1mf4 AND input2 IS input2_in2mf2 THEN output IS output_out1mf17 END
	   IF input1 IS input1_in1mf4 AND input2 IS input2_in2mf3 THEN output IS output_out1mf18 END
	   IF input1 IS input1_in1mf4 AND input2 IS input2_in2mf4 THEN output IS output_out1mf19 END
	   IF input1 IS input1_in1mf4 AND input2 IS input2_in2mf5 THEN output IS output_out1mf20 END
	   IF input1 IS input1_in1mf5 AND input2 IS input2_in2mf1 THEN output IS output_out1mf21 END
	   IF input1 IS input1_in1mf5 AND input2 IS input2_in2mf2 THEN output IS output_out1mf22 END
	   IF input1 IS input1_in1mf5 AND input2 IS input2_in2mf3 THEN output IS output_out1mf23 END
	   IF input1 IS input1_in1mf5 AND input2 IS input2_in2mf4 THEN output IS output_out1mf24 END
	   IF input1 IS input1_in1mf5 AND input2 IS input2_in2mf5 THEN output IS output_out1mf25 END
	QFIS_RULES_END
};
/* Rule strengths */
float rhStrength[25] = { 0.0f };

/* Parameters of the membership functions */
static const float input1_in1mf1_p[] = { 10.5959f, -0.0115f };
static const float input1_in1mf2_p[] = { 10.6064f, 25.0019f };
static const float input1_in1mf3_p[] = { 10.6209f, 49.9945f };
static const float input1_in1mf4_p[] = { 10.6184f, 74.9984f };
static const float input1_in1mf5_p[] = { 10.6209f, 99.9977f };
static const float input2_in2mf1_p[] = { 1.9923f, -0.0776f };
static const float input2_in2mf2_p[] = { 2.0137f, 4.1373f };
static const float input2_in2mf3_p[] = { 1.9107f, 8.5864f };
static const float input2_in2mf4_p[] = { 1.8814f, 12.9036f };
static const float input2_in2mf5_p[] = { 1.8354f, 17.2366f };
static const float output_out1mf1_p[] = { -0.1153f, -8.2286f, 2.3624f };
static const float output_out1mf2_p[] = { 0.6688f, -4.0748f, 9.3645f };
static const float output_out1mf3_p[] = { -1.4991f, -2.6764f, 24.9143f };
static const float output_out1mf4_p[] = { -7.8642f, 0.7403f, 99.0188f };
static const float output_out1mf5_p[] = { 36.5719f, -64.5631f, 311.2924f };
static const float output_out1mf6_p[] = { -0.1575f, -3.5282f, 5.2443f };
static const float output_out1mf7_p[] = { 0.0569f, -2.2587f, 6.4647f };
static const float output_out1mf8_p[] = { -0.2320f, -1.8344f, 23.5459f };
static const float output_out1mf9_p[] = { -0.1876f, -2.9150f, 41.3220f };
static const float output_out1mf10_p[] = { -0.3003f, -0.4349f, 18.1022f };
static const float output_out1mf11_p[] = { -0.3377f, -3.5827f, 12.8635f };
static const float output_out1mf12_p[] = { -0.0140f, -2.5795f, 13.3741f };
static const float output_out1mf13_p[] = { -0.2335f, -0.3314f, 15.1313f };
static const float output_out1mf14_p[] = { -0.1672f, -0.7311f, 18.3500f };
static const float output_out1mf15_p[] = { 0.0533f, 1.0645f, -20.2166f };
static const float output_out1mf16_p[] = { -0.6960f, 4.3821f, 48.2429f };
static const float output_out1mf17_p[] = { -0.3462f, 1.7457f, 12.1578f };
static const float output_out1mf18_p[] = { -0.5700f, -0.0662f, 37.5470f };
static const float output_out1mf19_p[] = { -0.7296f, -0.2992f, 53.6477f };
static const float output_out1mf20_p[] = { 0.2526f, -1.3879f, 3.3443f };
static const float output_out1mf21_p[] = { -2.5882f, -76.4197f, 275.4934f };
static const float output_out1mf22_p[] = { -13.8249f, -30.0337f, 1272.8725f };
static const float output_out1mf23_p[] = { -11.0501f, 13.6662f, 827.0861f };
static const float output_out1mf24_p[] = { -5.0887f, 26.7794f, 119.2481f };
static const float output_out1mf25_p[] = { -5.9659f, 23.7677f, 46.3556f };

void headtohead_init(void) {
	/* Set inputs */
	qFIS_InputSetup(headtohead_inputs, input1, 0.0010f, 100.0000f);
	qFIS_InputSetup(headtohead_inputs, input2, 0.0000f, 17.2376f);
	/* Set outputs */
	qFIS_OutputSetup(headtohead_outputs, output, -5.5000f, 3.5000f);
	/* Set membership functions for the inputs */
	qFIS_SetMF(MFin, input1, input1_in1mf1, gaussmf, NULL, input1_in1mf1_p, 1.0f);
	qFIS_SetMF(MFin, input1, input1_in1mf2, gaussmf, NULL, input1_in1mf2_p, 1.0f);
	qFIS_SetMF(MFin, input1, input1_in1mf3, gaussmf, NULL, input1_in1mf3_p, 1.0f);
	qFIS_SetMF(MFin, input1, input1_in1mf4, gaussmf, NULL, input1_in1mf4_p, 1.0f);
	qFIS_SetMF(MFin, input1, input1_in1mf5, gaussmf, NULL, input1_in1mf5_p, 1.0f);
	qFIS_SetMF(MFin, input2, input2_in2mf1, gaussmf, NULL, input2_in2mf1_p, 1.0f);
	qFIS_SetMF(MFin, input2, input2_in2mf2, gaussmf, NULL, input2_in2mf2_p, 1.0f);
	qFIS_SetMF(MFin, input2, input2_in2mf3, gaussmf, NULL, input2_in2mf3_p, 1.0f);
	qFIS_SetMF(MFin, input2, input2_in2mf4, gaussmf, NULL, input2_in2mf4_p, 1.0f);
	qFIS_SetMF(MFin, input2, input2_in2mf5, gaussmf, NULL, input2_in2mf5_p, 1.0f);
	/* Set membership functions for the outputs */
	qFIS_SetMF(MFout, output, output_out1mf1, linearmf, NULL, output_out1mf1_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf2, linearmf, NULL, output_out1mf2_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf3, linearmf, NULL, output_out1mf3_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf4, linearmf, NULL, output_out1mf4_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf5, linearmf, NULL, output_out1mf5_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf6, linearmf, NULL, output_out1mf6_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf7, linearmf, NULL, output_out1mf7_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf8, linearmf, NULL, output_out1mf8_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf9, linearmf, NULL, output_out1mf9_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf10, linearmf, NULL, output_out1mf10_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf11, linearmf, NULL, output_out1mf11_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf12, linearmf, NULL, output_out1mf12_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf13, linearmf, NULL, output_out1mf13_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf14, linearmf, NULL, output_out1mf14_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf15, linearmf, NULL, output_out1mf15_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf16, linearmf, NULL, output_out1mf16_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf17, linearmf, NULL, output_out1mf17_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf18, linearmf, NULL, output_out1mf18_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf19, linearmf, NULL, output_out1mf19_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf20, linearmf, NULL, output_out1mf20_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf21, linearmf, NULL, output_out1mf21_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf22, linearmf, NULL, output_out1mf22_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf23, linearmf, NULL, output_out1mf23_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf24, linearmf, NULL, output_out1mf24_p, 1.0f);
	qFIS_SetMF(MFout, output, output_out1mf25, linearmf, NULL, output_out1mf25_p, 1.0f);

	/* Configure the Inference System */
	qFIS_Setup(&headtohead, Sugeno,
		headtohead_inputs, sizeof(headtohead_inputs),
		headtohead_outputs, sizeof(headtohead_outputs),
		MFin, sizeof(MFin), MFout, sizeof(MFout),
		rules, rhStrength, 25u);
	qFIS_SetParameter(&headtohead, qFIS_AND, qFIS_PROD);
	qFIS_SetParameter(&headtohead, qFIS_OR, qFIS_PROBOR);
	qFIS_SetParameter(&headtohead, qFIS_Implication, qFIS_PROD);
	qFIS_SetParameter(&headtohead, qFIS_Aggregation, qFIS_SUM);
}

void headtohead_run(float* inputs, float* outputs) {
	/* Set the crips inputs */
	qFIS_SetInput(headtohead_inputs, input1, inputs[input1]);
	qFIS_SetInput(headtohead_inputs, input2, inputs[input2]);

	qFIS_Fuzzify(&headtohead);
	if (qFIS_Inference(&headtohead) > 0) {
		qFIS_DeFuzzify(&headtohead);
	}
	else {
		/* Error! */
	}

	/* Get the crips outputs */
	outputs[output] = qFIS_GetOutput(headtohead_outputs, output);
}