/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 12-Jun-2026 19:28:40 */
/* MATLAB Version: 9.14.0.2891782 (R2023a) Update 8 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#include "pathPlanning_fis.h"
#include "core/qfis.h"

/* FIS Object */
static qFIS_t pathPlanning;
/* I/O Fuzzy Objects */
static qFIS_Input_t pathPlanning_inputs[2];
static qFIS_Output_t pathPlanning_outputs[1];
/* I/O Membership Objects */
static qFIS_MF_t MFin[5], MFout[6];
/* I/O Names */
enum { selfSpeed, desiredSpeed };
enum { Acceleration };
/* I/O Membership functions tags */
enum { selfSpeed_slow, selfSpeed_fast, desiredSpeed_slow, desiredSpeed_medium, desiredSpeed_fast };
enum { Acceleration_out1mf1, Acceleration_out1mf2, Acceleration_out1mf3, Acceleration_out1mf4, Acceleration_out1mf5, Acceleration_out1mf6 };
/* Rules of the inference system */
static const qFIS_Rules_t rules[] = {
	QFIS_RULES_BEGIN
	   IF selfSpeed IS selfSpeed_slow AND desiredSpeed IS desiredSpeed_slow THEN Acceleration IS Acceleration_out1mf1 END
	   IF selfSpeed IS selfSpeed_slow AND desiredSpeed IS desiredSpeed_medium THEN Acceleration IS Acceleration_out1mf2 END
	   IF selfSpeed IS selfSpeed_slow AND desiredSpeed IS desiredSpeed_fast THEN Acceleration IS Acceleration_out1mf3 END
	   IF selfSpeed IS selfSpeed_fast AND desiredSpeed IS desiredSpeed_slow THEN Acceleration IS Acceleration_out1mf4 END
	   IF selfSpeed IS selfSpeed_fast AND desiredSpeed IS desiredSpeed_medium THEN Acceleration IS Acceleration_out1mf5 END
	   IF selfSpeed IS selfSpeed_fast AND desiredSpeed IS desiredSpeed_fast THEN Acceleration IS Acceleration_out1mf6 END
	QFIS_RULES_END
};
/* Rule strengths */
float rStrength[6] = { 0.0f };

/* Parameters of the membership functions */
static const float selfSpeed_slow_p[] = { 7.7200f, 0.0360f };
static const float selfSpeed_fast_p[] = { 7.7460f, 17.9500f };
static const float desiredSpeed_slow_p[] = { 3.1904f, 1.4098f };
static const float desiredSpeed_medium_p[] = { 3.4277f, 9.7672f };
static const float desiredSpeed_fast_p[] = { 3.4714f, 17.9974f };
static const float Acceleration_out1mf1_p[] = { -8.0984f, 0.9545f, -11.1076f };
static const float Acceleration_out1mf2_p[] = { 1.1723f, -0.5879f, 4.0368f };
static const float Acceleration_out1mf3_p[] = { 0.1071f, 2.1175f, -36.1781f };
static const float Acceleration_out1mf4_p[] = { -22.8076f, -4.5421f, 292.4655f };
static const float Acceleration_out1mf5_p[] = { -0.9961f, 0.8770f, -4.0909f };
static const float Acceleration_out1mf6_p[] = { -0.4831f, -0.8026f, 23.4096f };

void pathPlanning_init(void) {
	/* Set inputs */
	qFIS_InputSetup(pathPlanning_inputs, selfSpeed, 0.0000f, 17.9900f);
	qFIS_InputSetup(pathPlanning_inputs, desiredSpeed, 1.5990f, 18.0000f);
	/* Set outputs */
	qFIS_OutputSetup(pathPlanning_outputs, Acceleration, -5.5000f, 3.5000f);
	/* Set membership functions for the inputs */
	qFIS_SetMF(MFin, selfSpeed, selfSpeed_slow, gaussmf, NULL, selfSpeed_slow_p, 1.0f);
	qFIS_SetMF(MFin, selfSpeed, selfSpeed_fast, gaussmf, NULL, selfSpeed_fast_p, 1.0f);
	qFIS_SetMF(MFin, desiredSpeed, desiredSpeed_slow, gaussmf, NULL, desiredSpeed_slow_p, 1.0f);
	qFIS_SetMF(MFin, desiredSpeed, desiredSpeed_medium, gaussmf, NULL, desiredSpeed_medium_p, 1.0f);
	qFIS_SetMF(MFin, desiredSpeed, desiredSpeed_fast, gaussmf, NULL, desiredSpeed_fast_p, 1.0f);
	/* Set membership functions for the outputs */
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf1, linearmf, NULL, Acceleration_out1mf1_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf2, linearmf, NULL, Acceleration_out1mf2_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf3, linearmf, NULL, Acceleration_out1mf3_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf4, linearmf, NULL, Acceleration_out1mf4_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf5, linearmf, NULL, Acceleration_out1mf5_p, 1.0f);
	qFIS_SetMF(MFout, Acceleration, Acceleration_out1mf6, linearmf, NULL, Acceleration_out1mf6_p, 1.0f);

	/* Configure the Inference System */
	qFIS_Setup(&pathPlanning, Sugeno,
		pathPlanning_inputs, sizeof(pathPlanning_inputs),
		pathPlanning_outputs, sizeof(pathPlanning_outputs),
		MFin, sizeof(MFin), MFout, sizeof(MFout),
		rules, rStrength, 6u);
	qFIS_SetParameter(&pathPlanning, qFIS_AND, qFIS_PROD);
	qFIS_SetParameter(&pathPlanning, qFIS_OR, qFIS_PROBOR);
	qFIS_SetParameter(&pathPlanning, qFIS_Implication, qFIS_PROD);
	qFIS_SetParameter(&pathPlanning, qFIS_Aggregation, qFIS_SUM);
}

void pathPlanning_run(float* inputs, float* outputs) {
	/* Set the crips inputs */
	qFIS_SetInput(pathPlanning_inputs, selfSpeed, inputs[selfSpeed]);
	qFIS_SetInput(pathPlanning_inputs, desiredSpeed, inputs[desiredSpeed]);

	qFIS_Fuzzify(&pathPlanning);
	if (qFIS_Inference(&pathPlanning) > 0) {
		qFIS_DeFuzzify(&pathPlanning);
	}
	else {
		/* Error! */
	}

	/* Get the crips outputs */
	outputs[Acceleration] = qFIS_GetOutput(pathPlanning_outputs, Acceleration);
}