/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 12-Jun-2026 19:28:40 */
/* MATLAB Version: 9.14.0.2891782 (R2023a) Update 8 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#ifndef PATHPLANNING_FIS_H
#define PATHPLANNING_FIS_H

#ifdef __cplusplus
    extern "C" {
#endif

    void pathPlanning_init( void );
    void pathPlanning_run( float *inputs, float *outputs );

#ifdef __cplusplus
    }
#endif

#endif /* PATHPLANNING_FIS_H */
