/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 11-Jun-2026 22:27:23 */
/* MATLAB Version: 9.14.0.2891782 (R2023a) Update 8 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#ifndef RONDO2_FIS_H
#define RONDO2_FIS_H

#ifdef __cplusplus
    extern "C" {
#endif

    void rondo2_init( void );
    void rondo2_run( float *inputs, float *outputs );

#ifdef __cplusplus
    }
#endif

#endif /* RONDO2_FIS_H */
