/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 11-Jun-2026 22:27:23 */
/* MATLAB Version: 9.14.0.2891782 (R2023a) Update 8 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#include "rondo2_fis.h"
#include "core/qfis.h"

/* FIS Object */
static qFIS_t rondo2;
/* I/O Fuzzy Objects */
static qFIS_Input_t rondo2_inputs[2];
static qFIS_Output_t rondo2_outputs[1];
/* I/O Membership Objects */
static qFIS_MF_t MFin[10], MFout[5];
/* I/O Names */
enum { in1, in2 };
enum { out1 };
/* I/O Membership functions tags */
enum { in1_in1cluster1, in1_in1cluster2, in1_in1cluster3, in1_in1cluster4, in1_in1cluster5, in2_in2cluster1, in2_in2cluster2, in2_in2cluster3, in2_in2cluster4, in2_in2cluster5 };
enum { out1_out1cluster1, out1_out1cluster2, out1_out1cluster3, out1_out1cluster4, out1_out1cluster5 };
/* Rules of the inference system */
static const qFIS_Rules_t rules[] = {
	QFIS_RULES_BEGIN
	   IF in1 IS in1_in1cluster1 AND in2 IS in2_in2cluster1 THEN out1 IS out1_out1cluster1 END
	   IF in1 IS in1_in1cluster2 AND in2 IS in2_in2cluster2 THEN out1 IS out1_out1cluster2 END
	   IF in1 IS in1_in1cluster3 AND in2 IS in2_in2cluster3 THEN out1 IS out1_out1cluster3 END
	   IF in1 IS in1_in1cluster4 AND in2 IS in2_in2cluster4 THEN out1 IS out1_out1cluster4 END
	   IF in1 IS in1_in1cluster5 AND in2 IS in2_in2cluster5 THEN out1 IS out1_out1cluster5 END
	QFIS_RULES_END
};
/* Rule strengths */
float rStrength[5] = { 0.0f };

/* Parameters of the membership functions */
static const float in1_in1cluster1_p[] = { 3.1493f, 16.9761f };
static const float in1_in1cluster2_p[] = { 2.7829f, 6.6550f };
static const float in1_in1cluster3_p[] = { 2.5730f, 10.0079f };
static const float in1_in1cluster4_p[] = { 3.4952f, 7.4661f };
static const float in1_in1cluster5_p[] = { 3.0388f, 3.1295f };
static const float in2_in2cluster1_p[] = { 3.3037f, 17.7457f };
static const float in2_in2cluster2_p[] = { 2.4852f, 8.5675f };
static const float in2_in2cluster3_p[] = { 2.8084f, 17.6369f };
static const float in2_in2cluster4_p[] = { 2.7011f, 5.3039f };
static const float in2_in2cluster5_p[] = { 2.2598f, 18.2274f };
static const float out1_out1cluster1_p[] = { -0.5021f, 0.9818f, -8.3995f };
static const float out1_out1cluster2_p[] = { 0.1220f, -1.9196f, 25.2929f };
static const float out1_out1cluster3_p[] = { 0.0526f, -0.2152f, 6.0107f };
static const float out1_out1cluster4_p[] = { -0.7296f, -0.5387f, -2.9539f };
static const float out1_out1cluster5_p[] = { 0.5069f, 2.6821f, -46.8782f };

void rondo2_init(void) {
	/* Set inputs */
	qFIS_InputSetup(rondo2_inputs, in1, 1.0000f, 17.9913f);
	qFIS_InputSetup(rondo2_inputs, in2, 1.7524f, 18.0000f);
	/* Set outputs */
	qFIS_OutputSetup(rondo2_outputs, out1, -5.5000f, 3.5000f);
	/* Set membership functions for the inputs */
	qFIS_SetMF(MFin, in1, in1_in1cluster1, gaussmf, NULL, in1_in1cluster1_p, 1.0f);
	qFIS_SetMF(MFin, in1, in1_in1cluster2, gaussmf, NULL, in1_in1cluster2_p, 1.0f);
	qFIS_SetMF(MFin, in1, in1_in1cluster3, gaussmf, NULL, in1_in1cluster3_p, 1.0f);
	qFIS_SetMF(MFin, in1, in1_in1cluster4, gaussmf, NULL, in1_in1cluster4_p, 1.0f);
	qFIS_SetMF(MFin, in1, in1_in1cluster5, gaussmf, NULL, in1_in1cluster5_p, 1.0f);
	qFIS_SetMF(MFin, in2, in2_in2cluster1, gaussmf, NULL, in2_in2cluster1_p, 1.0f);
	qFIS_SetMF(MFin, in2, in2_in2cluster2, gaussmf, NULL, in2_in2cluster2_p, 1.0f);
	qFIS_SetMF(MFin, in2, in2_in2cluster3, gaussmf, NULL, in2_in2cluster3_p, 1.0f);
	qFIS_SetMF(MFin, in2, in2_in2cluster4, gaussmf, NULL, in2_in2cluster4_p, 1.0f);
	qFIS_SetMF(MFin, in2, in2_in2cluster5, gaussmf, NULL, in2_in2cluster5_p, 1.0f);
	/* Set membership functions for the outputs */
	qFIS_SetMF(MFout, out1, out1_out1cluster1, linearmf, NULL, out1_out1cluster1_p, 1.0f);
	qFIS_SetMF(MFout, out1, out1_out1cluster2, linearmf, NULL, out1_out1cluster2_p, 1.0f);
	qFIS_SetMF(MFout, out1, out1_out1cluster3, linearmf, NULL, out1_out1cluster3_p, 1.0f);
	qFIS_SetMF(MFout, out1, out1_out1cluster4, linearmf, NULL, out1_out1cluster4_p, 1.0f);
	qFIS_SetMF(MFout, out1, out1_out1cluster5, linearmf, NULL, out1_out1cluster5_p, 1.0f);

	/* Configure the Inference System */
	qFIS_Setup(&rondo2, Sugeno,
		rondo2_inputs, sizeof(rondo2_inputs),
		rondo2_outputs, sizeof(rondo2_outputs),
		MFin, sizeof(MFin), MFout, sizeof(MFout),
		rules, rStrength, 5u);
	qFIS_SetParameter(&rondo2, qFIS_AND, qFIS_PROD);
	qFIS_SetParameter(&rondo2, qFIS_OR, qFIS_PROBOR);
	qFIS_SetParameter(&rondo2, qFIS_Implication, qFIS_PROD);
	qFIS_SetParameter(&rondo2, qFIS_Aggregation, qFIS_SUM);
}

void rondo2_run(float* inputs, float* outputs) {
	/* Set the crips inputs */
	qFIS_SetInput(rondo2_inputs, in1, inputs[in1]);
	qFIS_SetInput(rondo2_inputs, in2, inputs[in2]);

	qFIS_Fuzzify(&rondo2);
	if (qFIS_Inference(&rondo2) > 0) {
		qFIS_DeFuzzify(&rondo2);
	}
	else {
		/* Error! */
	}

	/* Get the crips outputs */
	outputs[out1] = qFIS_GetOutput(rondo2_outputs, out1);
}